{
  "openapi": "3.1.0",
  "info": {
    "title": "api-settings",
    "version": "1.1"
  },
  "servers": [
    {
      "url": "https://api.aimtell.com"
    }
  ],
  "components": {
    "securitySchemes": {
      "sec0": {
        "type": "apiKey",
        "name": "X-Authorization-Api-Key",
        "in": "header",
        "x-default": ""
      }
    }
  },
  "security": [
    {
      "sec0": []
    }
  ],
  "paths": {
    "/prod/user/": {
      "get": {
        "summary": "Get User",
        "description": "",
        "operationId": "get-user",
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "uid": "76cedd11b19e",
                      "timezone": "America/Los_Angeles",
                      "registration_date": "2015-12-28 17:54:27",
                      "last_login": "2017-03-06 19:34:49",
                      "username": "demo@aimtell.com",
                      "auth_token": "AUTH_TOKEN_HERE",
                      "first_name": "Demo",
                      "last_name": "Aimtell",
                      "trial": 0,
                      "trial_end": "2016-12-07 17:54:50",
                      "teamId": null,
                      "wp": 0,
                      "shopify": 0,
                      "type": "intro"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Please specify a valid auth_token."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "x-readme": {
          "code-samples": [
            {
              "language": "curl",
              "code": "curl -XGET -H 'X-Authorization: AUTH_TOKEN' 'https://api.aimtell.com/prod/user/'"
            }
          ],
          "samples-languages": [
            "curl"
          ]
        },
        "tags": [
          "Users"
        ]
      },
      "put": {
        "summary": "Update User",
        "description": "",
        "operationId": "update-user",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "first_name": {
                    "type": "string",
                    "description": "First Name"
                  },
                  "last_name": {
                    "type": "string",
                    "description": "Last Name"
                  },
                  "password": {
                    "type": "string",
                    "description": "Password"
                  },
                  "timezone": {
                    "type": "string",
                    "description": "Timezone"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "success",
                      "message": "User updated.",
                      "user": {
                        "uid": "ia123d",
                        "timezone": "America/Los_Angeles",
                        "registration_date": "2014-10-05 00:00:00",
                        "last_login": "2015-10-01 04:03:20",
                        "username": "dj@aimtell.com",
                        "auth_token": "AUTH_TOKEN",
                        "first_name": "DJ",
                        "last_name": "Swanepoel",
                        "trial": "0",
                        "trial_end": "0000-00-00 00:00:00"
                      }
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "success"
                    },
                    "message": {
                      "type": "string",
                      "example": "User updated."
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "uid": {
                          "type": "string",
                          "example": "ia123d"
                        },
                        "timezone": {
                          "type": "string",
                          "example": "America/Los_Angeles"
                        },
                        "registration_date": {
                          "type": "string",
                          "example": "2014-10-05 00:00:00"
                        },
                        "last_login": {
                          "type": "string",
                          "example": "2015-10-01 04:03:20"
                        },
                        "username": {
                          "type": "string",
                          "example": "dj@aimtell.com"
                        },
                        "auth_token": {
                          "type": "string",
                          "example": "AUTH_TOKEN"
                        },
                        "first_name": {
                          "type": "string",
                          "example": "DJ"
                        },
                        "last_name": {
                          "type": "string",
                          "example": "Swanepoel"
                        },
                        "trial": {
                          "type": "string",
                          "example": "0"
                        },
                        "trial_end": {
                          "type": "string",
                          "example": "0000-00-00 00:00:00"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "text/plain": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Error #136."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Error #136."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Please specify a valid auth_token."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please specify a valid auth_token."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "x-readme": {
          "code-samples": [
            {
              "language": "curl",
              "code": "curl -XPUT -H 'X-Authorization: YOUR_AUTH_TOKEN' -H \"Content-type: application/json\" -d '{\n    \"first_name\": \"DJ\"\n}' 'https://api.aimtell.com/prod/user/ia123d'"
            }
          ],
          "samples-languages": [
            "curl"
          ]
        },
        "tags": [
          "Users"
        ]
      }
    }
  },
  "x-readme": {
    "headers": [],
    "explorer-enabled": true,
    "proxy-enabled": true
  },
  "x-readme-fauxas": true,
  "tags": [
    {
      "name": "Attributes",
      "description": "Custom attributes management"
    },
    {
      "name": "Authentication",
      "description": "Authentication and login endpoints"
    },
    {
      "name": "Triggered Notifications",
      "description": "Event-triggered campaigns"
    },
    {
      "name": "Push Notifications",
      "description": "Push notification delivery"
    },
    {
      "name": "RSS Notifications",
      "description": "RSS feed-based notifications"
    },
    {
      "name": "Users",
      "description": "User account management"
    },
    {
      "name": "Websites",
      "description": "Website management including settings, keys, permissions, and custom variables"
    },
    {
      "name": "Websites Settings",
      "description": "Website settings management"
    },
    {
      "name": "Websites Permissions",
      "description": "Website permissions management"
    }
  ]
}