{
  "openapi": "3.1.0",
  "info": {
    "title": "segmentation",
    "version": "1.1"
  },
  "servers": [
    {
      "url": "https://api.aimtell.com"
    }
  ],
  "components": {
    "securitySchemes": {
      "sec0": {
        "type": "apiKey",
        "name": "X-Authorization-Api-Key",
        "in": "header",
        "x-default": ""
      }
    }
  },
  "security": [
    {
      "sec0": []
    }
  ],
  "paths": {
    "/prod/segments/{idSite}": {
      "get": {
        "summary": "Get All Segments",
        "description": "Fetches all Segments for account",
        "operationId": "get-available-segments",
        "parameters": [
          {
            "name": "idSite",
            "in": "path",
            "description": "Site ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": [
                      {
                        "idsegment": 245,
                        "owner": "76cedd11b19e",
                        "name": "Sample Segment #1 - Lives In California",
                        "definition": "region==California",
                        "idSite": 179,
                        "createdAt": "2015-12-28 17:54:42",
                        "updatedAt": "2015-12-28 17:54:42",
                        "deleted": 0
                      },
                      {
                        "idsegment": 246,
                        "owner": "76cedd11b19e",
                        "name": "Sample Segment #2 - Viewed Tutorial Video",
                        "definition": "eventCategory==video,eventAction==tutorial",
                        "idSite": 179,
                        "createdAt": "2015-12-28 17:54:42",
                        "updatedAt": "2015-12-28 17:54:42",
                        "deleted": 0
                      },
                      {
                        "idsegment": 5909,
                        "owner": "76cedd11b19e",
                        "name": "Campaign for people who click certain links",
                        "definition": "pageUrl==https://josephmurphybrasil.com/",
                        "idSite": 179,
                        "createdAt": "2017-01-02 18:50:54",
                        "updatedAt": "2017-01-02 18:52:39",
                        "deleted": 0
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "idsegment": {
                        "type": "integer",
                        "example": 245,
                        "default": 0
                      },
                      "owner": {
                        "type": "string",
                        "example": "76cedd11b19e"
                      },
                      "name": {
                        "type": "string",
                        "example": "Sample Segment #1 - Lives In California"
                      },
                      "definition": {
                        "type": "string",
                        "example": "region==California"
                      },
                      "idSite": {
                        "type": "integer",
                        "example": 179,
                        "default": 0
                      },
                      "createdAt": {
                        "type": "string",
                        "example": "2015-12-28 17:54:42"
                      },
                      "updatedAt": {
                        "type": "string",
                        "example": "2015-12-28 17:54:42"
                      },
                      "deleted": {
                        "type": "integer",
                        "example": 0,
                        "default": 0
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Invalid token.",
                      "error_code": 71831
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid token."
                    },
                    "error_code": {
                      "type": "integer",
                      "example": 71831,
                      "default": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      }
    },
    "/prod/segment/{id}": {
      "get": {
        "summary": "Get Segment",
        "description": "Fetches a specific Segment",
        "operationId": "get-segment",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Segment ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "idsegment": 245,
                      "owner": "76cedd11b19e",
                      "name": "Sample Segment #1 - Lives In California",
                      "definition": "region==California",
                      "idSite": 179,
                      "createdAt": "2015-12-28 17:54:42",
                      "updatedAt": "2015-12-28 17:54:42",
                      "deleted": 0
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "idsegment": {
                      "type": "integer",
                      "example": 245,
                      "default": 0
                    },
                    "owner": {
                      "type": "string",
                      "example": "76cedd11b19e"
                    },
                    "name": {
                      "type": "string",
                      "example": "Sample Segment #1 - Lives In California"
                    },
                    "definition": {
                      "type": "string",
                      "example": "region==California"
                    },
                    "idSite": {
                      "type": "integer",
                      "example": 179,
                      "default": 0
                    },
                    "createdAt": {
                      "type": "string",
                      "example": "2015-12-28 17:54:42"
                    },
                    "updatedAt": {
                      "type": "string",
                      "example": "2015-12-28 17:54:42"
                    },
                    "deleted": {
                      "type": "integer",
                      "example": 0,
                      "default": 0
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Invalid token.",
                      "error_code": 71831
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid token."
                    },
                    "error_code": {
                      "type": "integer",
                      "example": 71831,
                      "default": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      },
      "put": {
        "summary": "Update Segment",
        "description": "Update a Specific Segment",
        "operationId": "update-segment",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Segment ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Name of Segment"
                  },
                  "definition": {
                    "type": "string",
                    "description": "Definition"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "success",
                      "idSegment": "24",
                      "message": "Successfully updated segment"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "success"
                    },
                    "idSegment": {
                      "type": "string",
                      "example": "24"
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully updated segment"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Error #136."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Error #136."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Please specify a valid auth_token."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please specify a valid auth_token."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      },
      "delete": {
        "summary": "Delete Segment",
        "description": "Delete a specific Segment",
        "operationId": "delete-segment",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Segment ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "success",
                      "idSegment": "5",
                      "message": "Successfully removed segment"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "success"
                    },
                    "idSegment": {
                      "type": "string",
                      "example": "5"
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully removed segment"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Please specify a valid auth_token."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please specify a valid auth_token."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      }
    },
    "/segment/{segment_id}/shared": {
      "get": {
        "summary": "Get Shared Segments",
        "description": "Get segments shared across websites using a segment ID",
        "operationId": "get-shared-segments",
        "parameters": [
          {
            "name": "segment_id",
            "in": "path",
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": [
                      {
                        "idsegment": 999220,
                        "idSite": 90001,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      },
                      {
                        "idsegment": 999221,
                        "idSite": 90002,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      },
                      {
                        "idsegment": 999222,
                        "idSite": 90003,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      },
                      {
                        "idsegment": 999223,
                        "idSite": 90004,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      },
                      {
                        "idsegment": 999224,
                        "idSite": 90005,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      },
                      {
                        "idsegment": 999225,
                        "idSite": 90006,
                        "shared_id": "5ef57e0e054fc1d22b1d99ab"
                      }
                    ]
                  }
                },
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "idsegment": {
                        "type": "integer",
                        "example": 999220,
                        "default": 0
                      },
                      "idSite": {
                        "type": "integer",
                        "example": 90001,
                        "default": 0
                      },
                      "shared_id": {
                        "type": "string",
                        "example": "5ef57e0e054fc1d22b1d99ab"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {}
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {}
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      }
    },
    "/prod/segments/": {
      "post": {
        "summary": "Create Segment",
        "description": "Create a NEW Segment",
        "operationId": "create-segment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "idSite"
                ],
                "properties": {
                  "idSite": {
                    "type": "string",
                    "description": "Site ID"
                  },
                  "name": {
                    "type": "string",
                    "description": "Name of Segment",
                    "default": ""
                  },
                  "definition": {
                    "type": "string",
                    "description": "Definition",
                    "default": ""
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "success",
                      "message": "Successfully created",
                      "id": 88
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "success"
                    },
                    "message": {
                      "type": "string",
                      "example": "Successfully created"
                    },
                    "id": {
                      "type": "integer",
                      "example": 88,
                      "default": 0
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Error #139."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Error #139."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      }
    },
    "/prod/segment/{id}/results": {
      "get": {
        "summary": "Get Segment Counts Over Time",
        "description": "Fetches a specific Segment",
        "operationId": "api-get-segment-counts-over-time",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Segment ID",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "startDate",
            "in": "query",
            "description": "Date as yyyy-mm-dd (i.e. 2019-12-07)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date",
              "default": ""
            }
          },
          {
            "name": "endDate",
            "in": "query",
            "description": "Date as yyyy-mm-dd (i.e. 2019-12-14)",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date",
              "default": ""
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "12/07/2019": 29,
                      "12/08/2019": 29,
                      "12/09/2019": 28,
                      "12/10/2019": 28,
                      "12/11/2019": 32,
                      "12/12/2019": 27,
                      "12/13/2019": 30,
                      "12/14/2019": 30
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "12/07/2019": {
                      "type": "integer",
                      "example": 29,
                      "default": 0
                    },
                    "12/08/2019": {
                      "type": "integer",
                      "example": 29,
                      "default": 0
                    },
                    "12/09/2019": {
                      "type": "integer",
                      "example": 28,
                      "default": 0
                    },
                    "12/10/2019": {
                      "type": "integer",
                      "example": 28,
                      "default": 0
                    },
                    "12/11/2019": {
                      "type": "integer",
                      "example": 32,
                      "default": 0
                    },
                    "12/12/2019": {
                      "type": "integer",
                      "example": 27,
                      "default": 0
                    },
                    "12/13/2019": {
                      "type": "integer",
                      "example": 30,
                      "default": 0
                    },
                    "12/14/2019": {
                      "type": "integer",
                      "example": 30,
                      "default": 0
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Invalid token.",
                      "error_code": 71831
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid token."
                    },
                    "error_code": {
                      "type": "integer",
                      "example": 71831,
                      "default": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Segments"
        ]
      }
    },
    "/prod/subscribers/{id}": {
      "get": {
        "summary": "Get Subscribers",
        "description": "Fetches all Subscribers for account",
        "operationId": "get-subscribers",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "description": "Site ID",
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "required": true
          },
          {
            "name": "limit",
            "in": "query",
            "description": "Limit",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "skip",
            "in": "query",
            "description": "Skip",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "segmentId",
            "in": "query",
            "description": "The ID of the segment you wish to filter by.",
            "schema": {
              "type": "integer",
              "format": "int32"
            }
          },
          {
            "name": "include",
            "in": "query",
            "description": "optionally include attributes",
            "schema": {
              "type": "string",
              "default": "attributes"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "count": 2,
                      "skip": 0,
                      "limit": 25,
                      "segmentId": null,
                      "filter": null,
                      "subscribers": [
                        {
                          "subscriber_uid": "c9603591-ffe0-ea08-8067-83420e5b4f5c",
                          "subscriberId": "c9603591-ffe0-ea08-8067-82478e5b4f5c",
                          "deviceType": "desktop",
                          "browserName": "Chrome",
                          "operatingSystemCode": "Mac OS X",
                          "browserLang": "en-US",
                          "region": "Virginia",
                          "city": "Ashburn",
                          "ip": "54.174.82.151",
                          "country": "United States",
                          "postal": "20149",
                          "idSite": 4240,
                          "createdAt": "2017-06-30 20:02:49"
                        },
                        {
                          "subscriber_uid": "d3428c3f-b78b-5563-042c-e3d49d98fa22",
                          "subscriberId": "d3428c3f-b26b-5563-042c-e3d49d98fa46",
                          "deviceType": "desktop",
                          "browserName": "Firefox",
                          "operatingSystemCode": "Mac OS X",
                          "browserLang": "en-US",
                          "region": "Virginia",
                          "city": "Ashburn",
                          "ip": "54.174.82.151",
                          "country": "United States",
                          "postal": "20149",
                          "idSite": 4240,
                          "createdAt": "2017-08-15 21:43:35"
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "integer",
                      "example": 2,
                      "default": 0
                    },
                    "skip": {
                      "type": "integer",
                      "example": 0,
                      "default": 0
                    },
                    "limit": {
                      "type": "integer",
                      "example": 25,
                      "default": 0
                    },
                    "segmentId": {},
                    "filter": {},
                    "subscribers": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "properties": {
                          "subscriber_uid": {
                            "type": "string",
                            "example": "c9603591-ffe0-ea08-8067-83420e5b4f5c"
                          },
                          "subscriberId": {
                            "type": "string",
                            "example": "c9603591-ffe0-ea08-8067-82478e5b4f5c"
                          },
                          "deviceType": {
                            "type": "string",
                            "example": "desktop"
                          },
                          "browserName": {
                            "type": "string",
                            "example": "Chrome"
                          },
                          "operatingSystemCode": {
                            "type": "string",
                            "example": "Mac OS X"
                          },
                          "browserLang": {
                            "type": "string",
                            "example": "en-US"
                          },
                          "region": {
                            "type": "string",
                            "example": "Virginia"
                          },
                          "city": {
                            "type": "string",
                            "example": "Ashburn"
                          },
                          "ip": {
                            "type": "string",
                            "example": "54.174.82.151"
                          },
                          "country": {
                            "type": "string",
                            "example": "United States"
                          },
                          "postal": {
                            "type": "string",
                            "example": "20149"
                          },
                          "idSite": {
                            "type": "integer",
                            "example": 4240,
                            "default": 0
                          },
                          "createdAt": {
                            "type": "string",
                            "example": "2017-06-30 20:02:49"
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Invalid token.",
                      "error_code": 71831
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid token."
                    },
                    "error_code": {
                      "type": "integer",
                      "example": 71831,
                      "default": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Subscribers"
        ]
      }
    },
    "/prod/subscribers/{idSite}": {
      "get": {
        "summary": "Get Subscriber",
        "description": "Fetches a specific Subscriber",
        "operationId": "get-subscriber",
        "parameters": [
          {
            "name": "idSite",
            "in": "path",
            "description": "Website ID",
            "schema": {
              "type": "integer",
              "format": "int32"
            },
            "required": true
          },
          {
            "name": "subscriber_uid",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "idSite": "300",
                      "subscriberId": "00388872-cd0b-4243-0333-642526c72f0f",
                      "browserLang": "ar",
                      "browserName": "Chrome",
                      "operatingSystemCode": "Windows",
                      "deviceType": "mobile",
                      "ip": "77.75.88.125",
                      "region": "Beyrouth",
                      "city": "Beirut",
                      "country": "Lebanon",
                      "custom_attributes": []
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "idSite": {
                      "type": "string",
                      "example": "300"
                    },
                    "subscriberId": {
                      "type": "string",
                      "example": "00388872-cd0b-4243-0333-642526c72f0f"
                    },
                    "browserLang": {
                      "type": "string",
                      "example": "ar"
                    },
                    "browserName": {
                      "type": "string",
                      "example": "Chrome"
                    },
                    "operatingSystemCode": {
                      "type": "string",
                      "example": "Windows"
                    },
                    "deviceType": {
                      "type": "string",
                      "example": "mobile"
                    },
                    "ip": {
                      "type": "string",
                      "example": "77.75.88.125"
                    },
                    "region": {
                      "type": "string",
                      "example": "Beyrouth"
                    },
                    "city": {
                      "type": "string",
                      "example": "Beirut"
                    },
                    "country": {
                      "type": "string",
                      "example": "Lebanon"
                    },
                    "custom_attributes": {
                      "type": "array"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Invalid token.",
                      "error_code": 71831
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Invalid token."
                    },
                    "error_code": {
                      "type": "integer",
                      "example": 71831,
                      "default": 0
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "tags": [
          "Subscribers"
        ]
      }
    },
    "/prod/subscriber": {
      "post": {
        "summary": "Track Subscriber Attribute",
        "description": "Track Subscriber Attribute",
        "operationId": "api-track-subscriber-attribute",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "idSite"
                ],
                "properties": {
                  "idSite": {
                    "type": "string",
                    "description": "Website ID"
                  },
                  "subscriber_uid": {
                    "type": "string",
                    "description": "Aimtell Subscriber ID"
                  },
                  "user": {
                    "type": "string",
                    "description": "Subscriber \"User\" Alias"
                  },
                  "email": {
                    "type": "string",
                    "description": "Subscriber \"Email\" Alias"
                  },
                  "attributes": {
                    "type": "string",
                    "description": "JSON",
                    "default": "",
                    "format": "json"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "200",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "success"
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "success"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "400",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Error #136."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Error #136."
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "401",
            "content": {
              "application/json": {
                "examples": {
                  "Result": {
                    "value": {
                      "result": "error",
                      "message": "Please specify a valid auth_token."
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "result": {
                      "type": "string",
                      "example": "error"
                    },
                    "message": {
                      "type": "string",
                      "example": "Please specify a valid auth_token."
                    }
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "x-readme": {
          "code-samples": [
            {
              "language": "curl",
              "code": "curl -XPOST -H 'X-Authorization-Api-Key: API_KEY' -H \"Content-type: application/json\" -d '{\n    \"idSite\": \"1\",\n    \"subscriber_uid\": \"5059b0a2-747d-0f74-73c4-24c8442de237\",\n    \"attributes\": {\n        \"first_name\" : \"jeff\",\n        \"gender\" : \"male\"\n    }\n}' 'https://api.aimtell.com/prod/subscriber/'",
              "name": "CURL (using subscriber_uid)"
            },
            {
              "language": "curl",
              "code": "curl -XPOST -H 'X-Authorization-Api-Key: API_KEY' -H \"Content-type: application/json\" -d '{\n    \"idSite\": \"1\",\n    \"user\": \"jeffdunham12\",\n    \"attributes\": {\n        \"first_name\" : \"jeff\",\n        \"gender\" : \"male\"\n    }\n}' 'https://api.aimtell.com/prod/subscriber/'",
              "name": "CURL (using user alias)"
            },
            {
              "language": "curl",
              "code": "curl -XPOST -H 'X-Authorization-Api-Key: API_KEY' -H \"Content-type: application/json\" -d '{\n    \"idSite\": \"1\",\n    \"email\": \"jeff@dunham.com\",\n    \"attributes\": {\n        \"first_name\" : \"jeff\",\n        \"gender\" : \"male\"\n    }\n}' 'https://api.aimtell.com/prod/subscriber/'",
              "name": "CURL (using email alias)"
            }
          ],
          "samples-languages": [
            "curl"
          ]
        },
        "tags": [
          "Subscribers"
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Segments",
      "description": "Audience segmentation"
    },
    {
      "name": "Subscribers",
      "description": "Subscriber management and tracking"
    }
  ]
}